import type { Metadata } from "next";
import { Geist, Geist_Mono, Yuji_Mai } from "next/font/google";
import "./globals.css";


const yujiMai = Yuji_Mai({
  weight: "400",
  display: "swap",
  style: "normal",
  variable: "--yuji",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spline by Vergil1000",
  description: "Generated by Vergil1000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} ${monomakh.variable} antialiased`}
        className={`${yujiMai.variable} antialiased vignette`}
      >
        {children}
      </body>
    </html>
  );
}
